### ISSUE TITLE
Use command line arguments to replace hardocded values

### ISSUE THREAD

**Issue by ronan-ln** [gimesketvirtadieni/slimstreamer#3]
The port the server runs on is hardcoded at the moment. It would be useful if instead, it could be set through a command line argument when running SlimStreamer.

In the same way, the audio device would be better passed with a command line argument (with a sensible default), to allow more flexibility for various setups.

**Comment by gimesketvirtadieni** [comment]
Support for command line options were introduced in v0.3.1-alpha. Looking forward for your feedback ;)
