### ISSUE TITLE
Squeezebox classic autodiscovery

### ISSUE THREAD

**Issue by ronan-ln** [gimesketvirtadieni/slimstreamer#4]
Hi,
I have managed to connect to to the SlimStreamer server with a squeezelite client, but I haven't been able to connect to the server from my squeezebox classic device.
The squeezebox doesn't let you input the IP of the server, so I cannot even try to connect that way.
I found online that there's a broadcast UDP packet sent for the player to discover the server.
Those links might be useful, although they mention different ports.
http://squeezecenter.slimdevices.narkive.com/APwd7mUI/slimdevices-squeezecenter-mdns-advertise-lms#post4
http://wiki.slimdevices.com/index.php/SLIMP3_client_protocol#.27d.27_-_Discovery_request

It would be great to have this added! Alternatively, is there a stream that I can pull from Slimstreamer?

Thanks,
Ronan

**Comment by gimesketvirtadieni** [comment]
Hi,
It's been implemented in [v0.6.0-beta](https://github.com/gimesketvirtadieni/slimstreamer/releases/tag/v0.6.0-beta).
Let me know if it does not work for you.
