### ISSUE TITLE
Playback lag

### ISSUE THREAD

**Issue by hd-info** [gimesketvirtadieni/slimstreamer#8]
I managed to set up everything: snd_aloop, SlimPlexor, slimstreamer, squeezelite on another machine pointing to server on slimstreamer machine.
I use aplay to play a wav sound file and it is playing on another machine via squeezelite. However, after some play there is a lag of several seconds and then playback resumes. What may be causing this?

I would also kindly ask you to look up an issue I opened in SlimPlexor project about selecting correct device via hw:x,y,z addressing.
Thank you!

**Comment by gimesketvirtadieni** [comment]
Hi. Few questions regarding that lag... It is one time lag or numerous? Is timing (when it occurs) is consistent or random?
I saw your question about device selection, I will answer it later today ;)

**Comment by hd-info** [comment]
There were numerous lags the first time but I was compiling the latest kernel in parallel so I attributed it to that.
When compiling finished I tried again and there was maybe 1, 1.5 minute of music then lag of several seconds but I think this was only lag. I can try again and time it this time if you want.

**Comment by hd-info** [comment]
I tried again couple of times and wasn't able to reproduce the lag. Strange thing happened second time: 5min song was finished and the, abruptly my two terminal windows were closed (one was running aplay, and other was running top), and last couple of seconds of song played again?!
Terminal window where SlimStreamer was running did not close.

**Comment by gimesketvirtadieni** [comment]
Hi. Two more questions: did you output logs to console (via your terminal) when this strange thing happened (if answer is yes then I think I know what happend)? What HW you use for SlimStreamer in terms of resources?

**Comment by gimesketvirtadieni** [comment]
Hi. I assume you were running SlimStreamer from your console in order to see the output (logs). Apparently there is a bug related to incorrect end of processing, which caused garbage to the output hence you got that weird behavior.
I am closing this issue and will respond about playback delay on your other issuer ;)
